### ISSUE TITLE
Implement additional checks when sending data

### ISSUE THREAD

**Issue by rbino** [astarte-platform/astarte-device-sdk-python#2]
- [ ] Check the interface is in the introspection
- [ ] Check the interface has device ownership
- [ ] Check the validity of the path
- [ ] Check the type of data is valid for that endpoint
- [ ] Check if the interface has `explicit_timestamp` when a timestamp is given (and viceversa)
